//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LmrPlast.DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.Deliveries = new HashSet<Deliveries>();
        }
    
        public int id_car { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public int YearOfIssue { get; set; }
        public Nullable<decimal> CapacityTons { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string AutoNum { get; set; }
        public Nullable<int> id_driver { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deliveries> Deliveries { get; set; }
    }
}
