//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LmrPlast.DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryCostCalculation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeliveryCostCalculation()
        {
            this.Deliveries = new HashSet<Deliveries>();
        }
    
        public int id { get; set; }
        public int id_delivery { get; set; }
        public int id_route { get; set; }
        public Nullable<decimal> FuelCost { get; set; }
        public int CostKM { get; set; }
        public decimal TotalDeliveryCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deliveries> Deliveries { get; set; }
        public virtual Deliveries Deliveries1 { get; set; }
        public virtual Route Route { get; set; }
    }
}
