//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LmrPlast.DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliveries
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deliveries()
        {
            this.DeliveryCostCalculation1 = new HashSet<DeliveryCostCalculation>();
        }
    
        public int id { get; set; }
        public int id_driver { get; set; }
        public int id_car { get; set; }
        public int id_responsible { get; set; }
        public int id_rout { get; set; }
        public Nullable<int> id_product { get; set; }
        public Nullable<int> id_category { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public System.DateTime ArrivalDate { get; set; }
        public int Product_quantity { get; set; }
        public Nullable<int> id_warehouse { get; set; }
        public int id_customer { get; set; }
        public string Status { get; set; }
        public Nullable<int> id_DeliveryCostCalculation { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Category Category { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual DeliveryCostCalculation DeliveryCostCalculation { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual Products Products { get; set; }
        public virtual Responsible Responsible { get; set; }
        public virtual Route Route { get; set; }
        public virtual Warehouses Warehouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryCostCalculation> DeliveryCostCalculation1 { get; set; }
        public virtual Cars Cars1 { get; set; }
    }
}
