//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LmrPlast.DateBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LmrPlastEntities6 : DbContext
    {
        public LmrPlastEntities6()
            : base("name=LmrPlastEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autho> Autho { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Deliveries> Deliveries { get; set; }
        public virtual DbSet<DeliveryCostCalculation> DeliveryCostCalculation { get; set; }
        public virtual DbSet<DepartureAddress> DepartureAddress { get; set; }
        public virtual DbSet<DestinationAddress> DestinationAddress { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Responsible> Responsible { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Warehouses> Warehouses { get; set; }
    }
}
