//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LmrPlast.DateBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Responsible
    {
        public int id { get; set; }
        public string FullName { get; set; }
        public string Post { get; set; }
        public int id_warehouse { get; set; }
    
        public virtual Deliveries Deliveries { get; set; }
        public virtual Warehouses Warehouses { get; set; }
    }
}
